{
 "title": "基金持股大盘2021.06",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   { "name": "stockname", "label": "股票名字" },
   { "name": "fundcode", "label": "基金号" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\nstockName AS \"股票名称\",\r\nstockCode AS \"股票代码\",\r\nequity AS \"占比\",\r\nholdingNum AS \"持有数量\",\r\nholdingPrice AS \"持仓价值\"\r\nFROM fund_holding WHERE fundCode =\"$fundcode\""
    }
   ]
  },
  { "title": "$stockname相关信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "持有$stockname的基金",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\t`name` as \"机构名\",\r\n\tequity as \"占比\"\r\nFROM\r\n\tfund_holding\r\n\tJOIN fund_info ON fundCode = `code` \r\nWHERE\r\n\tstockName = \"$stockname\""
    }
   ]
  },
  {
   "title": "$stockname累计买入金额(万元)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(holdingPrice)\nFROM fund_holding\nWHERE\n  stockName =\"$stockname\"\nORDER BY Time"
    }
   ]
  },
  { "title": "总体情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "机构爱买股票Top50",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  stockName as \"股票\",\n\tcount( stockName ) AS \"机构数\"\nFROM\n\tfund_holding\ngroup by stockName\nORDER BY count( stockName ) desc\n\tLIMIT 50"
    }
   ]
  },
  {
   "title": "成交量榜单(万元)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nSTR_TO_DATE(time,'%Y-%m-%d %H:%i:%s') AS 'time',\nstockName,\nsum(holdingPrice) AS 'total'\nFROM fund_holding\ngroup by stockName\norder by 'total' desc\nlimit 20"
    }
   ]
  },
  {
   "title": "累计买入(万元)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(holdingPrice)\nFROM fund_holding\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
    }
   ]
  }
 ]
}